"""unique quotes


Revision ID: 4ed1d8545ae3
Revises: 1fa11b138027
Create Date: 2025-04-06 14:28:07.534875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ed1d8545ae3'
down_revision: Union[str, None] = '1fa11b138027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_company_date', 'quote', ['date_', 'id_company'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_company_date', 'quote', type_='unique')
    # ### end Alembic commands ###
