"""holdings and returns

Revision ID: 92102acff41b
Revises: 4ed1d8545ae3
Create Date: 2025-04-14 10:50:33.562915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92102acff41b'
down_revision: Union[str, None] = '4ed1d8545ae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id_strategy', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id_strategy')
    )
    op.create_table('strategy_returns',
    sa.Column('id_strategy_return', sa.Integer(), nullable=False),
    sa.Column('id_strategy', sa.Integer(), nullable=False),
    sa.Column('date_', sa.Date(), nullable=True),
    sa.Column('return_', sa.Float(), nullable=True),
    sa.Column('cumulative_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_strategy'], ['strategies.id_strategy'], ),
    sa.PrimaryKeyConstraint('id_strategy_return')
    )
    op.create_table('strategy_transactions',
    sa.Column('id_strategy_transaction', sa.Integer(), nullable=False),
    sa.Column('id_strategy', sa.Integer(), nullable=False),
    sa.Column('nature', sa.Enum('BUY', 'SELL', name='strategytransactionnature'), nullable=True),
    sa.Column('date_', sa.Date(), nullable=True),
    sa.Column('conviction_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_strategy'], ['strategies.id_strategy'], ),
    sa.PrimaryKeyConstraint('id_strategy_transaction')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_transactions')
    op.drop_table('strategy_returns')
    op.drop_table('strategies')
    # ### end Alembic commands ###
